# Generated by Django 5.0.4 on 2024-08-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_lesson_homework_file_lesson_video_davomat_and_more'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='users.team'),
        ),
    ]
